# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-06-17 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageRouting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='ipaddress',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='prefix',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
